package com.jkjamies.omnivore.agent

import java.io.File

/**
 * Configuration for the Omnivore coverage agent.
 *
 * When used as a -javaagent, options are passed as:
 *   -javaagent:omnivore-agent.jar=destfile=/path/to/output.omnivore,includes=com.example.*
 */
data class AgentConfig(
    /** File path where execution data will be written on shutdown */
    val destFile: File = File("omnivore-coverage.omnivore"),

    /** Package include patterns (glob-style). Empty = include all. */
    val includes: List<String> = emptyList(),

    /** Package exclude patterns (glob-style) */
    val excludes: List<String> = emptyList(),

    /** Whether to filter Compose-generated bytecode */
    val composeFilterEnabled: Boolean = true,

    /** Additional Compose-generated class patterns to exclude */
    val composeExcludePatterns: List<String> = DEFAULT_COMPOSE_EXCLUDE_PATTERNS,
) {
    companion object {
        val DEFAULT_COMPOSE_EXCLUDE_PATTERNS = listOf(
            "*ComposableSingletons*",
            "*\$lambda-*",
            "*LiveLiterals*",
        )

        fun parse(agentArgs: String?): AgentConfig {
            if (agentArgs.isNullOrBlank()) return AgentConfig()

            val params = agentArgs.split(",").associate { param ->
                val (key, value) = param.split("=", limit = 2)
                key.trim() to value.trim()
            }

            return AgentConfig(
                destFile = params["destfile"]?.let { File(it) } ?: AgentConfig().destFile,
                includes = params["includes"]?.split(":") ?: emptyList(),
                excludes = params["excludes"]?.split(":") ?: emptyList(),
                composeFilterEnabled = params["compose"]?.toBooleanStrictOrNull() ?: true,
            )
        }
    }
}
