use crate::model::coverage::{CoverageSnapshot, FileCoverage};

/// Marker embedded in comments so we can find and update them.
pub const COMMENT_MARKER: &str = "<!-- omnivore-coverage-report -->";

/// Generate a Markdown PR comment comparing the current snapshot against an optional baseline.
pub fn generate_comment(
    current: &CoverageSnapshot,
    baseline: Option<&CoverageSnapshot>,
    dashboard_url: Option<&str>,
) -> String {
    let mut md = String::with_capacity(2048);

    md.push_str(COMMENT_MARKER);
    md.push('\n');
    md.push_str("## Omnivore Coverage Report\n\n");

    // Summary table
    md.push_str("| Metric | Value |");
    if baseline.is_some() {
        md.push_str(" Delta |");
    }
    md.push('\n');

    md.push_str("|---|---|");
    if baseline.is_some() {
        md.push_str("---|");
    }
    md.push('\n');

    // Line coverage row
    md.push_str(&format!(
        "| **Line Coverage** | {}% ({}/{}) |",
        fmt_pct(current.line_rate),
        current.lines_covered,
        current.lines_total,
    ));
    if let Some(base) = baseline {
        md.push_str(&format!(" {} |", fmt_delta(current.line_rate, base.line_rate)));
    }
    md.push('\n');

    // Branch coverage row
    md.push_str(&format!(
        "| **Branch Coverage** | {}% ({}/{}) |",
        fmt_pct(current.branch_rate),
        current.branches_covered,
        current.branches_total,
    ));
    if let Some(base) = baseline {
        md.push_str(&format!(" {} |", fmt_delta(current.branch_rate, base.branch_rate)));
    }
    md.push('\n');

    // Files row
    md.push_str(&format!("| **Files** | {} |", current.file_count));
    if let Some(base) = baseline {
        let diff = current.file_count - base.file_count;
        if diff != 0 {
            md.push_str(&format!(" {:+} |", diff));
        } else {
            md.push_str(" — |");
        }
    }
    md.push('\n');

    // Status badge
    md.push('\n');
    let status = if current.line_rate >= 0.8 {
        "🟢 **Passing** (≥ 80%)"
    } else if current.line_rate >= 0.5 {
        "🟡 **Warning** (≥ 50%)"
    } else {
        "🔴 **Failing** (< 50%)"
    };
    md.push_str(&format!("**Status:** {status}\n\n"));

    // File breakdown (top changed files if baseline exists, otherwise top 10 lowest)
    let current_files: Vec<FileCoverage> = current
        .files_json
        .as_deref()
        .and_then(|json| serde_json::from_str(json).ok())
        .unwrap_or_default();

    if !current_files.is_empty() {
        let baseline_files: Vec<FileCoverage> = baseline
            .and_then(|b| b.files_json.as_deref())
            .and_then(|json| serde_json::from_str(json).ok())
            .unwrap_or_default();

        let file_rows = build_file_table(&current_files, &baseline_files);
        if !file_rows.is_empty() {
            md.push_str("<details>\n<summary>File breakdown (click to expand)</summary>\n\n");
            md.push_str("| File | Coverage |");
            if !baseline_files.is_empty() {
                md.push_str(" Delta |");
            }
            md.push('\n');
            md.push_str("|---|---|");
            if !baseline_files.is_empty() {
                md.push_str("---|");
            }
            md.push('\n');

            for (path, rate, delta) in &file_rows {
                md.push_str(&format!("| `{}` | {}% |", path, fmt_pct(*rate)));
                if !baseline_files.is_empty() {
                    match delta {
                        Some(d) => md.push_str(&format!(" {} |", fmt_delta_val(*d))),
                        None => md.push_str(" 🆕 |"),
                    }
                }
                md.push('\n');
            }

            md.push_str("\n</details>\n\n");
        }
    }

    // Dashboard link
    if let Some(url) = dashboard_url {
        let project_url = format!("{}/projects/{}", url.trim_end_matches('/'), current.project_id);
        md.push_str(&format!("[View full report on Omnivore Dashboard]({})\n\n", project_url));
    }

    md.push_str("---\n*Generated by [Omnivore](https://github.com/jkjamies/coverage-tool)*\n");

    md
}

/// Build file table rows: (path, current_rate, delta_or_none).
/// Shows files with largest negative deltas first, then new files, then lowest coverage.
/// Caps at 15 files.
fn build_file_table(
    current: &[FileCoverage],
    baseline: &[FileCoverage],
) -> Vec<(String, f64, Option<f64>)> {
    use std::collections::HashMap;

    let base_map: HashMap<&str, f64> = baseline
        .iter()
        .map(|f| (f.path.as_str(), f.line_rate))
        .collect();

    let mut rows: Vec<(String, f64, Option<f64>)> = current
        .iter()
        .map(|f| {
            let delta = base_map.get(f.path.as_str()).map(|b| f.line_rate - b);
            (f.path.clone(), f.line_rate, delta)
        })
        .collect();

    if baseline.is_empty() {
        // No baseline — sort by lowest coverage
        rows.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));
    } else {
        // Sort: new files first, then by delta ascending (worst regressions first)
        rows.sort_by(|a, b| {
            match (&a.2, &b.2) {
                (None, Some(_)) => std::cmp::Ordering::Less,
                (Some(_), None) => std::cmp::Ordering::Greater,
                (Some(da), Some(db)) => da.partial_cmp(db).unwrap_or(std::cmp::Ordering::Equal),
                (None, None) => a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal),
            }
        });
    }

    rows.truncate(15);
    rows
}

fn fmt_pct(rate: f64) -> String {
    format!("{:.1}", rate * 100.0)
}

fn fmt_delta(current: f64, baseline: f64) -> String {
    fmt_delta_val(current - baseline)
}

fn fmt_delta_val(delta: f64) -> String {
    let pct = delta * 100.0;
    if pct.abs() < 0.05 {
        "—".to_string()
    } else if pct > 0.0 {
        format!("📈 +{:.1}%", pct)
    } else {
        format!("📉 {:.1}%", pct)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    fn make_snapshot(line_rate: f64, branch_rate: f64, files_json: Option<&str>) -> CoverageSnapshot {
        CoverageSnapshot {
            id: "snap-1".into(),
            project_id: "test-project".into(),
            commit_sha: Some("abc123".into()),
            branch: Some("feature/foo".into()),
            target: "JvmUnit".into(),
            line_rate,
            branch_rate,
            lines_covered: (line_rate * 100.0) as i64,
            lines_total: 100,
            branches_covered: (branch_rate * 50.0) as i64,
            branches_total: 50,
            file_count: 5,
            created_at: Utc::now(),
            files_json: files_json.map(|s| s.to_string()),
            dependencies_json: None,
        }
    }

    #[test]
    fn generates_comment_without_baseline() {
        let current = make_snapshot(0.78, 0.65, None);
        let md = generate_comment(&current, None, Some("https://omnivore.example.com"));

        assert!(md.contains(COMMENT_MARKER));
        assert!(md.contains("78.0%"));
        assert!(md.contains("Passing") || md.contains("Warning"));
        assert!(md.contains("omnivore.example.com"));
        // No delta column
        assert!(!md.contains("Delta"));
    }

    #[test]
    fn generates_comment_with_baseline_delta() {
        let current = make_snapshot(0.82, 0.70, None);
        let baseline = make_snapshot(0.75, 0.68, None);
        let md = generate_comment(&current, Some(&baseline), None);

        assert!(md.contains("Delta"));
        assert!(md.contains("📈")); // Coverage went up
        assert!(md.contains("Passing"));
    }

    #[test]
    fn generates_comment_with_regression() {
        let current = make_snapshot(0.45, 0.30, None);
        let baseline = make_snapshot(0.80, 0.70, None);
        let md = generate_comment(&current, Some(&baseline), None);

        assert!(md.contains("📉")); // Coverage went down
        assert!(md.contains("Failing"));
    }
}
