package com.jkjamies.omnivore.agent.instrumentation

import org.objectweb.asm.Opcodes
import org.objectweb.asm.tree.AnnotationNode
import org.objectweb.asm.tree.ClassNode
import org.objectweb.asm.tree.MethodNode

/**
 * Detects Compose-generated bytecode patterns that should be excluded
 * from coverage instrumentation.
 *
 * The Compose compiler generates significant synthetic bytecode that
 * JaCoCo incorrectly reports as uncovered. Omnivore skips instrumentation
 * of these patterns entirely, producing accurate coverage metrics.
 */
object ComposeDetector {

    private const val COMPOSABLE_DESCRIPTOR = "Landroidx/compose/runtime/Composable;"
    private const val COMPOSER_TYPE = "Landroidx/compose/runtime/Composer;"

    /** Class-level patterns that indicate entirely Compose-generated classes */
    private val GENERATED_CLASS_PATTERNS = listOf(
        "ComposableSingletons",
        "LiveLiterals\$",
        "\$ComposableFunction",
    )

    /**
     * Check if an entire class should be excluded from instrumentation.
     */
    fun isGeneratedClass(className: String): Boolean {
        return GENERATED_CLASS_PATTERNS.any { pattern ->
            className.contains(pattern)
        }
    }

    /**
     * Check if an entire class should be excluded based on custom patterns.
     */
    fun matchesExcludePattern(className: String, patterns: List<String>): Boolean {
        return patterns.any { pattern ->
            globMatches(pattern, className)
        }
    }

    /**
     * Check if a method is a Compose-generated lambda group.
     * These are methods like `$lambda-0`, `$lambda-1`, etc. that the Compose
     * compiler generates to wrap composable lambda expressions.
     */
    fun isComposeLambdaGroup(methodName: String): Boolean {
        return methodName.contains("\$lambda-") ||
            methodName.contains("\$lambda\$")
    }

    /**
     * Check if a method has the Compose compiler-injected $composer parameter.
     * Methods with @Composable annotation get a Composer parameter and an int
     * parameter ($changed) injected by the compiler.
     */
    fun hasComposerParameter(methodNode: MethodNode): Boolean {
        return methodNode.desc?.contains(COMPOSER_TYPE) == true
    }

    /**
     * Check if a method is annotated with @Composable.
     */
    fun isComposableMethod(methodNode: MethodNode): Boolean {
        return methodNode.visibleAnnotations?.any {
            it.desc == COMPOSABLE_DESCRIPTOR
        } == true || methodNode.invisibleAnnotations?.any {
            it.desc == COMPOSABLE_DESCRIPTOR
        } == true
    }

    /**
     * Determine which instructions in a composable method are compiler-generated
     * (and should not be instrumented) vs user-written logic (which should be).
     *
     * In a @Composable function, the Compose compiler inserts:
     * - startRestartGroup / endRestartGroup calls
     * - changed() checks on parameters
     * - skipToGroupEnd() calls
     * - updateScope lambda registration
     *
     * We want to instrument the user's actual logic (the body of the composable)
     * but skip the boilerplate the compiler wraps around it.
     */
    fun isComposeBoilerplateMethod(methodName: String): Boolean {
        val boilerplatePatterns = listOf(
            "startRestartGroup",
            "endRestartGroup",
            "startReplaceableGroup",
            "endReplaceableGroup",
            "startMovableGroup",
            "endMovableGroup",
            "skipToGroupEnd",
            "sourceInformation",
            "sourceInformationMarkerStart",
            "sourceInformationMarkerEnd",
            "updateScope",
        )
        return boilerplatePatterns.any { methodName.contains(it) }
    }

    /**
     * Check if a class node represents a Compose-generated class by examining
     * its structure (annotations, inner classes, etc.)
     */
    fun isGeneratedClass(classNode: ClassNode): Boolean {
        val className = classNode.name ?: return false

        // Check name patterns
        if (isGeneratedClass(className)) return true

        // Check for Compose compiler metadata annotation
        val hasComposeMetadata = classNode.visibleAnnotations?.any {
            it.desc?.contains("StabilityInferred") == true
        } == true

        // If it's a synthetic inner class with Compose metadata, likely generated
        if (hasComposeMetadata &&
            (classNode.access and Opcodes.ACC_SYNTHETIC) != 0
        ) {
            return true
        }

        return false
    }

    private fun globMatches(pattern: String, text: String): Boolean {
        val regex = pattern
            .replace(".", "\\.")
            .replace("*", ".*")
            .replace("?", ".")
        return Regex(regex).matches(text)
    }
}
