package com.jkjamies.omnivore.agent.reporter

import java.io.File

/**
 * Writes a self-contained HTML coverage report for local viewing.
 */
object HtmlReportWriter {

    fun write(outputFile: File, analysisResult: CoverageAnalyzer.AnalysisResult) {
        outputFile.parentFile?.mkdirs()

        val summary = analysisResult.summary
        val linePercent = "%.1f".format(summary.lineRate * 100)
        val branchPercent = "%.1f".format(summary.branchRate * 100)

        val fileRows = analysisResult.files.joinToString("\n") { file ->
            val fileLinePercent = "%.1f".format(file.lineRate * 100)
            val fileBranchPercent = "%.1f".format(file.branchRate * 100)
            val covered = file.lines.count { it.hitCount > 0 }
            val total = file.lines.size
            val barColor = when {
                file.lineRate >= 0.8 -> "#4caf50"
                file.lineRate >= 0.5 -> "#ff9800"
                else -> "#f44336"
            }
            """
            <tr>
                <td class="file-path">${escapeHtml(file.path)}</td>
                <td class="coverage-bar">
                    <div class="bar-bg">
                        <div class="bar-fill" style="width: ${fileLinePercent}%; background: $barColor;"></div>
                    </div>
                </td>
                <td class="percent">$fileLinePercent%</td>
                <td class="fraction">$covered/$total</td>
                <td class="percent">$fileBranchPercent%</td>
            </tr>
            """.trimIndent()
        }

        val html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Omnivore Coverage Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #1a1a2e; color: #e0e0e0; padding: 24px; }
        h1 { color: #fff; margin-bottom: 8px; font-size: 24px; }
        .subtitle { color: #888; margin-bottom: 24px; font-size: 14px; }
        .summary { display: flex; gap: 24px; margin-bottom: 32px; }
        .summary-card { background: #16213e; border-radius: 8px; padding: 20px; flex: 1; }
        .summary-card .label { color: #888; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; }
        .summary-card .value { font-size: 36px; font-weight: bold; margin-top: 4px; }
        .summary-card .detail { color: #888; font-size: 14px; margin-top: 4px; }
        .green { color: #4caf50; }
        .yellow { color: #ff9800; }
        .red { color: #f44336; }
        table { width: 100%; border-collapse: collapse; background: #16213e; border-radius: 8px; overflow: hidden; }
        th { text-align: left; padding: 12px 16px; background: #0f3460; color: #888; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; }
        td { padding: 10px 16px; border-top: 1px solid #1a1a3e; }
        .file-path { font-family: 'SF Mono', 'Fira Code', monospace; font-size: 13px; }
        .percent { text-align: right; font-weight: 600; width: 80px; }
        .fraction { text-align: right; color: #888; width: 80px; font-size: 13px; }
        .coverage-bar { width: 200px; }
        .bar-bg { background: #1a1a2e; border-radius: 4px; height: 8px; overflow: hidden; }
        .bar-fill { height: 100%; border-radius: 4px; transition: width 0.3s; }
        tr:hover { background: #1a1a3e; }
    </style>
</head>
<body>
    <h1>Omnivore Coverage Report</h1>
    <p class="subtitle">Generated by Omnivore Coverage Agent</p>

    <div class="summary">
        <div class="summary-card">
            <div class="label">Line Coverage</div>
            <div class="value ${colorClass(summary.lineRate)}">$linePercent%</div>
            <div class="detail">${summary.linesCovered} / ${summary.linesTotal} lines</div>
        </div>
        <div class="summary-card">
            <div class="label">Branch Coverage</div>
            <div class="value ${colorClass(summary.branchRate)}">$branchPercent%</div>
            <div class="detail">${summary.branchesCovered} / ${summary.branchesTotal} branches</div>
        </div>
        <div class="summary-card">
            <div class="label">Files</div>
            <div class="value">${analysisResult.files.size}</div>
            <div class="detail">${analysisResult.files.count { it.lineRate >= 0.8 }} with good coverage</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>File</th>
                <th>Coverage</th>
                <th>Lines %</th>
                <th>Lines</th>
                <th>Branches %</th>
            </tr>
        </thead>
        <tbody>
$fileRows
        </tbody>
    </table>
</body>
</html>
        """.trimIndent()

        outputFile.writeText(html)
    }

    private fun colorClass(rate: Double): String = when {
        rate >= 0.8 -> "green"
        rate >= 0.5 -> "yellow"
        else -> "red"
    }

    private fun escapeHtml(text: String): String = text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
}
