package com.jkjamies.omnivore.agent.reporter

import java.io.File

/**
 * Writes a Markdown coverage report suitable for PR comments, CI logs, or READMEs.
 */
object MarkdownReportWriter {

    fun write(outputFile: File, analysisResult: CoverageAnalyzer.AnalysisResult) {
        outputFile.parentFile?.mkdirs()
        outputFile.writeText(generate(analysisResult))
    }

    fun generate(analysisResult: CoverageAnalyzer.AnalysisResult): String {
        val summary = analysisResult.summary
        val linePercent = "%.1f".format(summary.lineRate * 100)
        val branchPercent = "%.1f".format(summary.branchRate * 100)

        return buildString {
            appendLine("## Omnivore Coverage Report")
            appendLine()
            appendLine("| Metric | Coverage | Details |")
            appendLine("|--------|----------|---------|")
            appendLine("| Lines | ${badge(summary.lineRate)} **${linePercent}%** | ${summary.linesCovered} / ${summary.linesTotal} |")
            appendLine("| Branches | ${badge(summary.branchRate)} **${branchPercent}%** | ${summary.branchesCovered} / ${summary.branchesTotal} |")
            appendLine("| Files | | ${analysisResult.files.size} total, ${analysisResult.files.count { it.lineRate >= 0.8 }} with good coverage |")
            appendLine()

            if (analysisResult.files.isNotEmpty()) {
                appendLine("### Per-file coverage")
                appendLine()
                appendLine("| File | Lines % | Lines | Branches % |")
                appendLine("|------|---------|-------|------------|")

                for (file in analysisResult.files) {
                    val fileLinePercent = "%.1f".format(file.lineRate * 100)
                    val fileBranchPercent = "%.1f".format(file.branchRate * 100)
                    val covered = file.lines.count { it.hitCount > 0 }
                    val total = file.lines.size
                    appendLine("| `${file.path}` | ${badge(file.lineRate)} ${fileLinePercent}% | ${covered}/${total} | ${fileBranchPercent}% |")
                }
                appendLine()
            }

            appendLine("---")
            appendLine("*Generated by [Omnivore Coverage](https://github.com/omnivore-coverage)*")
        }
    }

    private fun badge(rate: Double): String = when {
        rate >= 0.8 -> "\uD83D\uDFE2" // green circle
        rate >= 0.5 -> "\uD83D\uDFE1" // yellow circle
        else -> "\uD83D\uDD34"         // red circle
    }
}
